### PR TITLE
Support for "include" parameter for command line tools as well as where clause parameters for each inclusion

### PR DESCRIPTION
**Pull request by dzholmukhanov**
I am planning to probably integrate the utility into our project in production. It needs to be able to export only specific tables with specific records from the database. I thought this feature might be useful for everyone.

### CODE REVIEW

**Comment by ErikEJ** [comment]
Thank for a great contribution

**Comment by dzholmukhanov** [comment]
Thanks for the great program!

**Comment by ErikEJ** [comment]
https://twitter.com/ErikEJ/status/1071393142061047808 !!

**Comment by dzholmukhanov** [comment]
Thank you 👍 I appreaciate that :)

**Pull request merged**
