### PR TITLE
Added support for filtered indexes

### LINKED ISSUE #759: Filtered index WHERE clause not included when converting an MsSQL database to SQLite
Filtered index `WHERE` clause not included when converting an MsSQL database to SQLite.

### Steps to reproduce
Create an MsSQL database with a table that contains an index with a `WHERE` clause.
For example, create a nullable `nvarchar(256)` column named `Column1` and the following index:
```
CREATE UNIQUE NONCLUSTERED INDEX [UK_Column1]
    ON [dbo].[Table1]([Column1] ASC) WHERE ([Column1] IS NOT NULL);
```

When the database is converted to SQLite, the index doesn't include the `WHERE` clause.

### Further technical details
I'm using the API directly.
SQL Server 2014
Visual Studio 2015 14.0.25431.01 Update 3

### PR DESCRIPTION
**Pull request by icnocop**
Fixed typo in "Foreign"
Fixes #759

### CODE REVIEW

**Comment by ErikEJ** [comment]
Thanks for the PR - but please make it smaller and single purpose (it looks like you are doing 3 or 4 different things here at the same time: Filtered indexes, something with foreign key triggers, correcting a spelling mistake and code refactoring)

**Comment by icnocop** [comment]
I created https://github.com/ErikEJ/SqlCeToolbox/pull/761 for the typo in "Foreign".

Thank you.

**Comment by icnocop** [comment]
I created PR https://github.com/ErikEJ/SqlCeToolbox/pull/762 for generating foreign key insert and update triggers.

**Comment by ErikEJ** [comment]
Thanks! I will update the scripting libs after this PR

**Pull request merged**
