### PR TITLE
Fixed composite foreign keys bug (Issue 885)

### PR DESCRIPTION
**Pull request by gsv-helbling**
SQLite triggers generated for composite foreign keys have a clause of the form:
```sql
WHERE (SELECT Id1, ..., IdN FROM ForeignTable WHERE Id1 = NEW.ForeignId1 AND ... AND IdN = NEW.ForeignIdN) IS NULL
```

When the trigger is executed you get an "N Columns when 1 Expected" error, because the subquery return N columns.

The hacky solution would be to replace `... IS NULL` with `... IS (NULL, ..., NULL)` where NULL appears N time.

The more robust solution proposed in the pull request replaces the null check with a more robust EXISTS clause of the form:
```sql
WHERE NOT EXISTS (SELECT * FROM ForeignTable WHERE Id1 = NEW.ForeignId1 AND ... AND IdN = NEW.ForeignIdN)
```

### CODE REVIEW

**Comment by gsv-helbling** [comment]
Good thing you asked, I just assumed my fix worked and actually wrote the opposite of what I should have written.
I could test the fixed code by directly binding into the `SqlCeScripting40.dll`, and my fix now actually solves the problem we encountered (tested on a private db).

I would like to leave to you the job of adding a test for the fix and binding the DLL into the GUI / VS tool, as I don't have enough time to learn how to make this contribution.

Here is a minimal schema to reproduce the problem
```sql
CREATE TABLE [Owner] (
  [OwnerId1] uniqueidentifier NOT NULL
, [OwnerId2] uniqueidentifier NOT NULL
, PRIMARY KEY ([OwnerId1],[OwnerId2])
);

CREATE TABLE [Product] (
  [ProductId] uniqueidentifier NOT NULL
, [OwnerId1] uniqueidentifier NOT NULL
, [OwnerId2] uniqueidentifier NOT NULL
, PRIMARY KEY ([NoOfflineTestId])
, CONSTRAINT [FK_Product_Owner] FOREIGN KEY ([OwnerId1], [OwnerId2]) REFERENCES [Owner] ([OwnerId1], [OwnerId2])
);
```

Here is how the trigger would have been generated for SQLite before the fix:
```sql
CREATE TRIGGER [fki_Product_OwnerId_Owner_OwnerId]
BEFORE Insert ON [Product] FOR EACH ROW BEGIN SELECT RAISE(ROLLBACK, 'Insert on table Product violates foreign key constraint FK_Product_Owner')
WHERE (SELECT OwnerId1, OwnerId2 FROM Patient WHERE  OwnerId1 = NEW.OwnerId1 AND OwnerId2 = NEW.OwnerId2) IS NULL; END;
```

And with the fix:
```sql
CREATE TRIGGER [fki_Product_OwnerId_Owner_OwnerId]
BEFORE Insert ON [Product] FOR EACH ROW BEGIN SELECT RAISE(ROLLBACK, 'Insert on table Product violates foreign key constraint FK_Product_Owner')
WHERE NOT EXISTS (SELECT OwnerId1, OwnerId2 FROM Patient WHERE  OwnerId1 = NEW.OwnerId1 AND OwnerId2 = NEW.OwnerId2); END;
```

**Comment by ErikEJ** [comment]
If you open the SqlCeScripting solution, there is a test project. It should be possible to add a test there.  I will Update the GUI after your PR is in, no worries.

**Comment by gsv-helbling** [comment]
As requested, I added a test. It is a bit long if compared with tests in the same section, but I ensured that it passes with my proposed fix, and doesn't pass without.

**Comment by ErikEJ** [comment]
@gsv-helbling Thanks, this is now in the latest daily build

**Comment by gsv-helbling** [comment]
@ErikEJ Thank you for being so quick!

**Pull request merged**
